# MySQL. Versions 8.0.27 and up are supported.
# Developed on MySQL Versions 8.0.27 for Win64 on x86_64 (MySQL Community Server - GPL)
# Resource: 
# - Install MySQL: https://dev.mysql.com/downloads/installer/
# Project: Practice Management Portal
#---------------------------------------------------------------------------------------

default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  database: practice_management_portal

development:
  <<: *default
  host: localhost
  username: pmp_development
  password: <%= ENV.fetch("MYSQL_PSWD_DEV") { PASSword@123 } %>

test:
  <<: *default
  host: localhost
  username: pmp_testing
  password: <%= ENV.fetch("MYSQL_PSWD_TEST") { PASSword@123 } %>

production:
  <<: *default
  host: <%= ENV.fetch("MYSQL_PRODUCTION_HOST") { localhost } %>
  reconnect: true
  socket: /tmp/mysql.sock
  port: 3306
  username: pmp_production
  password: <%= ENV.fetch("MYSQL_PSWD_PROD") { PASSword@123 } %>
